os:
  - linux
language: node_js
node_js:
  - "6"
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key:
    secure: $NPM_API_KEY
  on:
    branch: master
